services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development # 개발용 단계 선택
    image: petmily-api:dev
    container_name: petmily-dev-container
    ports:
      - '8080:8080'
    env_file:
      - .env.dev
    environment:
      - DB_HOST=host.docker.internal # DB_HOST 덮어쓰기

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production # 프로덕션용 단계 선택
    image: petmily-api:prod
    container_name: petmily-prod-container
    ports:
      - '8080:8080'
    env_file:
      - .env.prod
